# Generated by Django 4.2 on 2023-04-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dukan_user',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('add_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('pancard_number', models.CharField(blank=True, max_length=15, null=True)),
                ('adhaar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('email_address', models.CharField(blank=True, max_length=150, null=True)),
                ('is_mobile_verify', models.IntegerField(blank=True, default=0, null=True)),
                ('is_email_verify', models.IntegerField(blank=True, default=0, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('lat', models.CharField(blank=True, max_length=20, null=True)),
                ('lng', models.CharField(blank=True, max_length=20, null=True)),
                ('km', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('r_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('contact_id', models.CharField(max_length=40)),
                ('review', models.TextField(blank=True, null=True)),
                ('add_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('ratting', models.IntegerField(blank=True, default=5, null=True)),
            ],
        ),
    ]
