# Generated by Django 4.2 on 2023-04-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dukan_user',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='dukan_user',
            name='lng',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
