# Generated by Django 4.2 on 2023-04-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukaan', '0002_dukan_user_media_alter_dukan_user_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='dukan_user',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dukan_user',
            name='reviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
