# Generated by Django 4.2 on 2023-04-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukaan', '0003_dukan_user_category_dukan_user_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dukan_user',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
