# Generated by Django 4.2 on 2023-04-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukaan', '0004_alter_dukan_user_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('remark', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('mobile_number', models.ImageField(blank=True, null=True, upload_to='')),
                ('add_date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
