# Generated by Django 4.0.2 on 2023-04-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukaan', '0006_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dukan_user',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='dukan_user',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dukan_user',
            name='shop_name',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
